---
# Zmienne
# marcin_stec@pl.ibm.com
pkgs:
  - zsh
  - zsh-syntax-highlighting
  - mc
  - git
  - nmon
  - bind-utils
  - tmux
  - powerline
  - vim-powerline
  - tmux-powerline
  - powerline-fonts
  - wget
  - curl
  - ruby
  - ruby-devel 
  - util-linux-user
  - redhat-rpm-config 
  - gcc
  - gcc-c++ 
  - make
  - nethogs
  - fontawesome-fonts   # to może nie działać na RH <= 8 

# Paczki debianowe/ubuntowe
debs: 
  - zsh
  - git
  - powerline
  - powerline-gitstatus
  - zsh-theme-powerlevel9k
  - tmux
  - nmon
  - nethogs

# Lista grup administracyjnych zależy od distro
Debian_grps: "adm,sudo"
Ubuntu_grps: "{{ Debian_grps }}"
RedHat_grps: "wheel"
Fedora_grps: "{{ RedHat_grps }}" # Ro rozożniania używam ansible_os_family, więć Fedora i tak dostanie RedHat ale na wszelki wypadek zostawiam

# Tymczasowy katalog roboczy wzgędem domowego
work_dir: "{{ ansible_env.HOME }}/work"
