---
# Zmienne dla PCSS
  ansible_user: "ibm"
  my_user: "ibm"
  my_gecos: "Ajbiem Juzer"
  ansible_python_interpreter: "/usr/bin/python3"
  # ansible_python_interpreter: "/usr/bin/python3.9" # To się pierdoli z python3-dnf na RH8
