---
# Brudnopis
# marcin_stec@pl.ibm.com
- hosts: all
  gather_facts: True
  remote_user: marcinek
  become: True

  tasks:
    # - name: pokaż fakty
    #   debug:
    #     var: ansible_facts
    # - name: yum-yum
    #   block:
    #     - name: Sciąganie repozytorium EPEL
    #       debug:
    #         msg: "Distro: {{ ansible_facts['distribution'] }}"

      # when: ansible_facts['pkg_mgr'] == 'yum'
    - name: Przygotowanie EPEL dla RHEL7
      block:
        - name: Gra wstępna RHEL7
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: subscription-manager repos --enable rhel-*-optional-rpms --enable rhel-*-extras-rpms --enable rhel-ha-for-rhel-*-server-rpms
        - name: Instlacja EPEL
          yum:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

    - name: Przygotowanie EPEL dla RHEL8
      block:
        - name: Gra wstępna RHEL8
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

    - name: Przygotowanie EPEL dla RHEL9
      block:
        - name: Gra wstępna RHEL9
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'

    - name: Przygotowanie EPEL dla CentOS 7
      yum:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

    - name: Przygotowanie EPEL dla CentOS 8
      block:
        - name: Gra wstępna CentOS8
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: dnf config-manager --set-enabled powertools
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '8'

    - name: Przygotowanie EPEL dla CentOS 9
      block:
        - name: Gra wstępna CentOS9
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: dnf config-manager --set-enabled crb
        - name: Instlacja EPEL
          dnf:
            name: item
            state: present
          with_items:
            - epel-release 
            - epel-next-release
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '9'