---
# Brudnopis
# marcin_stec@pl.ibm.com
- hosts: all
  gather_facts: True
  remote_user: marcinek
  become: True

  tasks:
    - set_fact: user_grps={{ ansible_os_family }}_grps
    # - name: pokaż fakty
    #   debug:
    #     var: ansible_facts
    
    - name: Pokaż paczkomat
      debug:
        msg: "Distro: {{ ansible_facts['distribution'] }}"
      tags:
        - "DBG"
      # when: ansible_facts['pkg_mgr'] == 'yum'
    
    - name: Określanie listy grup w zależności od distro
      debug:
        msg: "Zastosuję {{ user_grps}} do zakładania użyszkodnika"
    
    - name: Instalacja specyfików dla Powerline+ZSH dla systemów Debianów
      block:
        - name: Warunkowe wykoanie bloku dla "bebianów"
          debug:
            msg: "Jestem Debianopodobny"
      when: ansible_os_family == 'Debian'

    - name: Instalacja specyfików dla Powerline+ZSH dla systemów RedHatopodobnych
      block:
        - name: Warunkowe wykoanie bloku dla "bebianów"
          debug:
            msg: "Jestem Debianopodobny"
      when: ansible_os_family == 'Debian'