---
# Stałe elementy gry przy instalacji nowego Linuxa do pracy
# marcin_stec@pl.ibm.com
- hosts: all
  gather_facts: True
  remote_user: marcinek
  become: True

  roles:
    - role: epel    # Włącznie repo EPEL dla dystrybucji, któ©e tego potrzebują
      when: ansible_os_family == 'RedHat'

    - role: web_srv
      when: web_server
      tags:
        - "WEBSERVER"

  tasks:
    # ustalam listę grup dla usera w zależności od os family
    - set_fact: user_grps={{ ansible_os_family }}_grps
      tags:
        - always
   
    - name: Ulubione paczki na Yum-Yumach
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'yum'
      tags:
        - "PKGS"

    - name: Ulubione paczki na nowszych OSach
      dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'dnf'
      tags:
        - "PKGS"

    - name: Ulubione paczki na mniej ulibionych OSach
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debs }}"
      when: ansible_facts['pkg_mgr'] == 'apt'
      tags:
        - "PKGS"


    - name: Kolarze do sudo
      copy:
        src: wheel
        dest: /etc/sudoers.d/
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'RedHat'
      tags:
        - "USER"

    - name: śmierć śmiertelnikom, czyli sudoersi do sudo
      copy:
        src: sudo
        dest: /etc/sudoers.d/
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'
      tags:
        - "USER"

    - name: Dodawanie Marcinka
      user:
        name: marcinek
        comment: "Marcin Steć"
        generate_ssh_key: True
        ssh_key_type: ed25519
        groups: "{{ vars[user_grps] }}"
        shell: /usr/bin/zsh
        password: "{{ marcinek_pass }}"   # pochodzi z @vars/secrets.enc, które nie jest wrzucane do gita
        update_password: "on_create"
      register: marcinek_data
      tags:
        - "USER"

    - name: zshrc dla marcinka
      copy:
        src: zshrc-pre-powerline10k
        dest: "{{ marcinek_data.home }}/.zshrc"
        owner: marcinek
        group: marcinek
        mode: 0644
        force: false
      tags:
        - "USER"
        - "ZSH"

    - name: zakładanie katalogu roboczego do instalacji czcionek
      file:
        path: "{{ work_dir }}"
        state: directory
      tags:
        - "USER"
        - "ZSH"

    - name: Klonowanie repo czcionek nerdowych dla oh-my-zsh
      command: 
        cmd: git clone --depth=1 https://github.com/ryanoasis/nerd-fonts
        chdir: "{{ work_dir }}"
        creates: "{{ work_dir }}/nerd-fonts"
      when: 
      tags:
        - "USER"
        - "ZSH"
    
    - name: Instalowanie czcionek nerdowych dla oh-my-zsh (systemowo)
      command: 
        cmd: ./install.sh -S
        chdir: "{{ work_dir }}/nerd-fonts"
        creates: "/usr/local/share/fonts/NerdFonts" 
      tags:
        - "ZSH"

    - block:
      # Chrum-chrum dla usera marcinek. Trzeba się nim stać wcześniej, bo "creates" sprawdzane jest dla
      # ansible_user a nie dla become 
      - name: Uruchamianie skryptu instalacynego oh-my-zsh dla marcinka
        shell: 
          cmd: sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" "" --unattended
          creates: "{{ marcinek_data.home }}/.zshrc.pre-oh-my-zsh"
        tags:
          - "OH-MY-ZSH"

      - name: Ściąganie powerlevel10k dla marcinka
        shell: 
          cmd: git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/themes/powerlevel10k
          creates: "{{ marcinek_data.home }}/.oh-my-zsh/themes/powerlevel10k"
        tags:
          - "OH-MY-ZSH"
          - "P10K"
      
      - name: Ustawainie tematu ZSH na powerlevel10k
        lineinfile:
          path: "{{ marcinek_data.home }}/.zshrc"
          regexp: '^ZSH_THEME='
          line: ZSH_THEME=powerlevel10k/powerlevel10k
        tags:
          - "OH-MY-ZSH"
          - "P10K"

      - name: Wmulanie ulubionego konfigu p10k
        copy:
          src: cfg-p10k.zsh
          dest: "{{ marcinek_data.home }}/.p10k.zsh"
          owner: marcinek
          group: marcinek
          mode: 0644
        tags:
          - "OH-MY-ZSH"
          - "P10K"

      become: yes
      become_user: marcinek
  
    - name: Strefa czasowa
      timezone:
        name: Europe/Warsaw
      tags:
        - "TZ"