---
# Stałe elementy gry przy instalacji nowego Linuxa do pracy
# marcin_stec@pl.ibm.com
- hosts: all
  gather_facts: True
  remote_user: root

  tasks:


    - name: Przygotowanie EPEL dla RHEL7
      block:
        - name: Gra wstępna RHEL7
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: subscription-manager repos --enable rhel-*-optional-rpms --enable rhel-*-extras-rpms --enable rhel-ha-for-rhel-*-server-rpms
        - name: Instlacja EPEL
          yum:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

    - name: Przygotowanie EPEL dla RHEL8
      block:
        - name: Włączanie wymaganych repozytoriów
          command: "subscription-manager repos --enable codeready-builder-for-rhel-8-{{ ansible_facts['architecture'] }}-rpms"
        - name: Import klucza GPG dla EPEL
          rpm_key:
            state: present
            key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

    - name: Przygotowanie EPEL dla RHEL9
      block:
        - name: Włączanie wymaganych repozytoriów
          command: "subscription-manager repos --enable codeready-builder-for-rhel-9-{{ ansible_facts['architecture'] }}-rpms"
        - name: Import klucza GPG dla EPEL
          rpm_key:
            state: present
            key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'

    - name: Przygotowanie EPEL dla CentOS 7
      yum:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

    - name: Przygotowanie EPEL dla CentOS 8
      block:
        - name: Gra wstępna CentOS8
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: dnf config-manager --set-enabled powertools
        - name: Instlacja EPEL
          dnf:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            state: present
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '8'

    - name: Przygotowanie EPEL dla CentOS 9
      block:
        - name: Gra wstępna CentOS9
          debug:
            msg: "Distro: {{ ansible_facts['distribution'] }}, Wersja: {{ ansible_facts['distribution_major_version'] }}"
        - name: Włączanie wymaganych repozytoriów
          command: dnf config-manager --set-enabled crb
        - name: Instlacja EPEL
          dnf:
            name: "{{ item }}"
            state: present
          with_items:
            - epel-release 
            - epel-next-release
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '9'

    - name: Ulubione paczki na Yum-Yumach
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'yum'
      tags:
        - "PKGS"

    - name: Ulubione paczki na nowszych OSach
      dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'dnf'
      tags:
        - "PKGS"

    - name: Kolarze do sudo
      copy:
        src: wheel
        dest: /etc/sudoers.d/
        owner: root
        group: root
        mode: 0644
      tags:
        - "USER"
    - name: Dodawanie Marcinka
      user:
        name: marcinek
        comment: "Marcin Steć"
        generate_ssh_key: True
        ssh_key_type: ecdsa
        groups: wheel
        shell: /usr/bin/zsh
        password: "{{ marcinek_pass }}"   # pochodzi z @vars/secrets.enc, które nie jest wrzucane do gita
        update_password: "on_create"
      tags:
        - "USER"

    - name: zshrc dla marcinka
      copy:
        src: zshrc-pre-powerline10k
        dest: /home/marcinek/.zshrc
        owner: marcinek
        group: marcinek
        mode: 0644
      tags:
        - "USER"
        - "ZSH"

    - name: Instlacja czcionek dla oh-my-zsh
  
      command: 
      when: ansible_facts.selinux.status == 'enabled'
      tags:  