---
# Stałe elementy gry przy instalacji nowego Linuxa do pracy
# marcin_stec@pl.ibm.com
- hosts: all
  gather_facts: True
  remote_user: marcinek
  become: True

  roles:
    - role: epel    # Włącznie repo EPEL dla dystrybucji, któ©e tego potrzebują
      when: ansible_os_family == 'RedHat'

  tasks:
    # ustalam listę grup dla usera w zależności od os family
    - set_fact: user_grps={{ ansible_os_family }}_grps
   
    - name: Ulubione paczki na Yum-Yumach
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'yum'
      tags:
        - "PKGS"

    - name: Ulubione paczki na nowszych OSach
      dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
      when: ansible_facts['pkg_mgr'] == 'dnf'
      tags:
        - "PKGS"

    - name: Ulubione paczki na mniej ulibionych OSach
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debs }}"
      when: ansible_facts['pkg_mgr'] == 'apt'
      tags:
        - "PKGS"


    - name: Kolarze do sudo
      copy:
        src: wheel
        dest: /etc/sudoers.d/
        owner: root
        group: root
        mode: 0644
      # when: ansible_os_family == 'RedHat'
      tags:
        - "USER"

    - name: Dodawanie Marcinka
      user:
        name: marcinek
        comment: "Marcin Steć"
        generate_ssh_key: True
        ssh_key_type: ecdsa
        groups: "{{ vars[user_grps] }}"
        shell: /usr/bin/zsh
        password: "{{ marcinek_pass }}"   # pochodzi z @vars/secrets.enc, które nie jest wrzucane do gita
        update_password: "on_create"
      tags:
        - "USER"

    - name: zshrc dla marcinka
      copy:
        src: zshrc-pre-powerline10k
        dest: /home/marcinek/.zshrc
        owner: marcinek
        group: marcinek
        mode: 0644
      tags:
        - "USER"
        - "ZSH"

    # - name: Instlacja czcionek dla oh-my-zsh
  
    #   command: 
    #   when: ansible_facts.selinux.status == 'enabled'
    #   tags:  
    # - name: Instalacja specyfików dla Powerline+ZSH dla systemów RedHatopodobnych
    #   block:
    #     - name: 